### ISSUE TITLE
Is go-sox thread safe

### ISSUE THREAD

**Issue by lixinswitchpi** [krig/go-sox#19]
I tried to use the go-sox in multiple threads access that it is for multiple HTTP streaming audio convert, but when I start the second thread, it will crash as below shows
--------------------
main: effects_i_dsp.c:168: init_fft_cache: Assertion `lsx_fft_br == ((void *)0)' failed.
INFO[0018] call: --> ACCEPT 16777232                    
SIGABRT: abort
PC=0x7f7dc0a02277 m=7 sigcode=18446744073709551610
signal arrived during cgo execution

goroutine 31 [syscall, locked to thread]:
runtime.cgocall(0x8bc0f0, 0xc42002b700, 0x0)
	/usr/local/go/src/runtime/cgocall.go:132 +0xe4 fp=0xc42002b6d0 sp=0xc42002b690 pc=0x412bd4
github.com/krig/go-sox._Cfunc_sox_init(0x0)
	github.com/krig/go-sox/_obj/_cgo_gotypes.go:713 +0x49 fp=0xc42002b700 sp=0xc42002b6d0 pc=0x73aff9
github.com/krig/go-sox.Init(0x0)
	/root/work/src/github.com/krig/go-sox/sox.go:134 +0x22 fp=0xc42002b718 sp=0xc42002b700 pc=0x73b982
git.xxxxtech.com/xxxxcloud/dataprocessor.(*Dataprocessor).NewProducer.func1(0xc42014a600, 0xc420143360, 0xc420135890)
	/root/work/src/git.xxxxtech.com/xxxxcloud/dataprocessor/dprocessor.go:46 +0x34 fp=0xc42002b7c8 sp=0xc42002b718 pc=0x7414e4
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2337 +0x1 fp=0xc42002b7d0 sp=0xc42002b7c8 pc=0x46df21
created by git.xxxxtech.com/xxxxcloud/dataprocessor.(*Dataprocessor).NewProducer
	/root/work/src/git.xxxxtech.com/xxxxcloud/dataprocessor/dprocessor.go:45 +0xa0

goroutine 1 [semacquire]:
sync.runtime_Semacquire(0xc4201440fc)
	/usr/local/go/src/runtime/sema.go:56 +0x39
sync.(*WaitGroup).Wait(0xc4201440f0)
	/usr/local/go/src/sync/waitgroup.go:131 +0x72
main.run(0xc420196000)
	/root/work/src/git.xxxxtech.com/xxxxcloud/main/main.go:162 +0x7e6
github.com/urfave/cli.HandleAction(0x90e680, 0x9ef578, 0xc420196000, 0xc4201541e0, 0x0)
	/root/work/src/github.com/urfave/cli/app.go:503 +0x7c
github.com/urfave/cli.(*App).Run(0xc420190000, 0xc420010090, 0x3, 0x3, 0x0, 0x0)
	/root/work/src/github.com/urfave/cli/app.go:268 +0x653
main.main()
	/root/work/src/git.xxxxtech.com/xxxxcloud/main/main.go:70 +0x72e

goroutine 5 [syscall]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:131 +0xa6
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.0
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x41

goroutine 8 [chan receive]:
git.xxxxtech.com/xxxxcloud/eventsprocessor.(*g_System).Exit.func1(0xc420154300, 0xc420132820)
	/root/work/src/git.xxxxtech.com/xxxxcloud/eventsprocessor/eprocessor.go:61 +0x4b
created by git.xxxxtech.com/xxxxcloud/eventsprocessor.(*g_System).Exit
	/root/work/src/git.xxxxtech.com/xxxxcloud/eventsprocessor/eprocessor.go:60 +0xe9

goroutine 18 [chan receive]:
gopkg.in/natefinch/lumberjack%2ev2.(*Logger).millRun(0xc420154240)
	/root/work/src/gopkg.in/natefinch/lumberjack.v2/lumberjack.go:379 +0x58
created by gopkg.in/natefinch/lumberjack%2ev2.(*Logger).mill.func1
	/root/work/src/gopkg.in/natefinch/lumberjack.v2/lumberjack.go:390 +0x7e

goroutine 19 [chan receive]:
database/sql.(*DB).connectionOpener(0xc42019e000)
	/usr/local/go/src/database/sql/sql.go:871 +0x53
created by database/sql.Open
	/usr/local/go/src/database/sql/sql.go:609 +0x1ee

goroutine 7 [IO wait]:
internal/poll.runtime_pollWait(0x7f7dc20e9f70, 0x72, 0xffffffffffffffff)
	/usr/local/go/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc42011e118, 0x72, 0xc420040c00, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0xae
internal/poll.(*pollDesc).waitRead(0xc42011e118, 0xffffffffffffff00, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Accept(0xc42011e100, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:334 +0x1e2
net.(*netFD).accept(0xc42011e100, 0x7f7dc2145000, 0x0, 0x9eff00)
	/usr/local/go/src/net/fd_unix.go:238 +0x42
net.(*TCPListener).accept(0xc42000e148, 0xc420040e78, 0x422358, 0x30)
	/usr/local/go/src/net/tcpsock_posix.go:136 +0x2e
net.(*TCPListener).AcceptTCP(0xc42000e148, 0xc4201b8210, 0xc4201b8210, 0x930700)
	/usr/local/go/src/net/tcpsock.go:234 +0x49
net/http.tcpKeepAliveListener.Accept(0xc42000e148, 0xc4200140a0, 0x930700, 0xe5b6d0, 0x9aea40)
	/usr/local/go/src/net/http/server.go:3120 +0x2f
net/http.(*Server).Serve(0xc4200752b0, 0xe734e0, 0xc42000e148, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:2695 +0x1b2
net/http.(*Server).ListenAndServe(0xc4200752b0, 0xc420060300, 0x0)
	/usr/local/go/src/net/http/server.go:2636 +0xa9
created by git.xxxxtech.com/xxxxcloud/api.Run
	/root/work/src/git.xxxxtech.com/xxxxcloud/api/api.go:22 +0x11b

goroutine 21 [chan receive]:
git.xxxxtech.com/xxxxcloud/api.Run(0xc4201429c0)
	/root/work/src/git.xxxxtech.com/xxxxcloud/api/api.go:26 +0x155
created by main.run
	/root/work/src/git.xxxxtech.com/xxxxcloud/main/main.go:144 +0x6af

goroutine 22 [select, locked to thread]:
runtime.gopark(0x9efdd8, 0x0, 0x9c1f36, 0x6, 0x18, 0x1)
	/usr/local/go/src/runtime/proc.go:277 +0x12c
runtime.selectgo(0xc42003af50, 0xc42014a1e0)
	/usr/local/go/src/runtime/select.go:395 +0x1138
runtime.ensureSigM.func1()
	/usr/local/go/src/runtime/signal_unix.go:511 +0x220
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2337 +0x1

goroutine 9 [runnable, locked to thread]:
git.xxxxtech.com/hmp/grandprix-go._Cfunc_PKX_SYSTEM_WaitOnEvent(0xffffffff, 0xc4201888a0, 0xc400000000)
	git.xxxxtech.com/hmp/grandprix-go/_obj/_cgo_gotypes.go:2612 +0x4d
git.xxxxtech.com/hmp/grandprix-go.systemWaitOnEvent(0xc4ffffffff, 0xc420053bc8, 0x2, 0x2)
	/root/work/src/git.xxxxtech.com/hmp/grandprix-go/system_hmp.go:63 +0x47
git.xxxxtech.com/hmp/grandprix-go.SystemWaitOnEvent(0xc4ffffffff, 0x2, 0x2, 0xc420144b28)
	/root/work/src/git.xxxxtech.com/hmp/grandprix-go/system.go:22 +0x29
git.xxxxtech.com/xxxxcloud/eventsprocessor.(*g_System).EventProcess(0xc420132820)
	/root/work/src/git.xxxxtech.com/xxxxcloud/eventsprocessor/eprocessor.go:88 +0x60
main.run.func1(0xc4201440f0, 0xc420132820)
	/root/work/src/git.xxxxtech.com/xxxxcloud/main/main.go:160 +0x51
created by main.run
	/root/work/src/git.xxxxtech.com/xxxxcloud/main/main.go:158 +0x7d5

goroutine 23 [select]:
net/http.(*persistConn).readLoop(0xc4200a3680)
	/usr/local/go/src/net/http/transport.go:1654 +0x7a7
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1186 +0xa2e

goroutine 16 [select]:
git.xxxxtech.com/xxxxcloud/rbuffer.NewEQ.func1(0xc4200e1820)
	/root/work/src/git.xxxxtech.com/xxxxcloud/rbuffer/eq.go:30 +0x444
created by git.xxxxtech.com/xxxxcloud/rbuffer.NewEQ
	/root/work/src/git.xxxxtech.com/xxxxcloud/rbuffer/eq.go:25 +0x157

goroutine 24 [select]:
net/http.(*persistConn).writeLoop(0xc4200a3680)
	/usr/local/go/src/net/http/transport.go:1759 +0x165
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1187 +0xa53

goroutine 34 [IO wait]:
internal/poll.runtime_pollWait(0x7f7dc20e9df0, 0x72, 0x0)
	/usr/local/go/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc42011e618, 0x72, 0xffffffffffffff00, 0xe6fce0, 0xe6b240)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0xae
internal/poll.(*pollDesc).waitRead(0xc42011e618, 0xc4201e9b00, 0x6101, 0x6101)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc42011e600, 0xc4201e9bff, 0x6101, 0x6101, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:125 +0x18a
net.(*netFD).Read(0xc42011e600, 0xc4201e9bff, 0x6101, 0x6101, 0x1bff, 0x0, 0x0)
	/usr/local/go/src/net/fd_unix.go:202 +0x52
net.(*conn).Read(0xc4201400b0, 0xc4201e9bff, 0x6101, 0x6101, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:176 +0x6d
net/http.(*persistConn).Read(0xc4200a3680, 0xc4201e9bff, 0x6101, 0x6101, 0x43bb78, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:1391 +0x140
bufio.(*Reader).Read(0xc420154540, 0xc4201e9bff, 0x6101, 0x6101, 0x43b4b9, 0xc400000008, 0xc4201ba780)
	/usr/local/go/src/bufio/bufio.go:199 +0x1a3
net/http.(*body).readLocked(0xc4201ba980, 0xc4201e9bff, 0x6101, 0x6101, 0x1bff, 0x0, 0x0)
	/usr/local/go/src/net/http/transfer.go:779 +0x67
net/http.(*body).Read(0xc4201ba980, 0xc4201e9bff, 0x6101, 0x6101, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/transfer.go:771 +0xea
net/http.(*bodyEOFSignal).Read(0xc4201ba9c0, 0xc4201e9bff, 0x6101, 0x6101, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:2124 +0xe9
io.ReadAtLeast(0xe6dfa0, 0xc4201ba9c0, 0xc4201e8000, 0x7d00, 0x7d00, 0x7d00, 0x947ec0, 0x7f7d70000800, 0xe6dfa0)
	/usr/local/go/src/io/io.go:309 +0x86
io.ReadFull(0xe6dfa0, 0xc4201ba9c0, 0xc4201e8000, 0x7d00, 0x7d00, 0xc4201e1de0, 0x469fe0, 0xc4201c8780)
	/usr/local/go/src/io/io.go:327 +0x58
git.xxxxtech.com/xxxxcloud/dataprocessor.(*Dataprocessor).Read(0xc4201b9170, 0x0, 0x0, 0x0)
	/root/work/src/git.xxxxtech.com/xxxxcloud/dataprocessor/dprocessor.go:76 +0xc9
git.xxxxtech.com/xxxxcloud/dataprocessor.(*Dataprocessor).NewProducer.func1(0xc42001c7e0, 0xc4200e1820, 0xc4201b9170)
	/root/work/src/git.xxxxtech.com/xxxxcloud/dataprocessor/dprocessor.go:66 +0x76
created by git.xxxxtech.com/xxxxcloud/dataprocessor.(*Dataprocessor).NewProducer
	/root/work/src/git.xxxxtech.com/xxxxcloud/dataprocessor/dprocessor.go:45 +0xa0

goroutine 35 [select]:
net/http.(*persistConn).readLoop(0xc4201505a0)
	/usr/local/go/src/net/http/transport.go:1654 +0x7a7
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1186 +0xa2e

goroutine 30 [select]:
git.xxxxtech.com/xxxxcloud/rbuffer.NewEQ.func1(0xc420143360)
	/root/work/src/git.xxxxtech.com/xxxxcloud/rbuffer/eq.go:30 +0x444
created by git.xxxxtech.com/xxxxcloud/rbuffer.NewEQ
	/root/work/src/git.xxxxtech.com/xxxxcloud/rbuffer/eq.go:25 +0x157

goroutine 36 [select]:
net/http.(*persistConn).writeLoop(0xc4201505a0)
	/usr/local/go/src/net/http/transport.go:1759 +0x165
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1187 +0xa53

rax    0x0
rbx    0x7f7dc2193000
rcx    0xffffffffffffffff
rdx    0x6
rdi    0x10aa
rsi    0x10be
rbp    0x7f7dc0b56580
rsp    0x7f7da526eb58
r8     0x0
r9     0x7f7d8c00b250
r10    0x8
r11    0x206
r12    0x7f7dc0e0e64c
r13    0x7f7dc0e0eaf0
r14    0x1
r15    0x0
rip    0x7f7dc0a02277
rflags 0x206
cs     0x33
fs     0x0
gs     0x0
[root@localhost main]#

**Comment by krig** [comment]
It is not thread safe, no.

**Comment by jjhesk** [comment]
it is not thread safe and has a race condition
